### ISSUE TITLE
ElasticSearch Plugin non-functional with current ElasticSearch

### ISSUE THREAD

**Issue by tomschlenkhoff** [bro/bro-plugins#16]
Due to changes in ElasticSearch (2.0) the plugin is broken.

Field names may not contain dots: https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_mapping_changes.html#_field_names_may_not_contain_dots

Error message:

`[2016-02-05 11:31:00,443][DEBUG][action.bulk              ] [g201] [bro-201602050300][1] failed to execute bulk item (index) index {[bro-201602050300][dns][AVKxMxLVuWGvJSEWQ-w_], source[{"ts":1454650903074,"uid":"CmkvLO3Ojc0GmQvKwb","id.orig_h":"10.10.0.6","id.orig_p":51893,"id.resp_h":"213.133.98.98","id.resp_p":53,"proto":"udp","trans_id":34820,"query":"graph.facebook.com","qclass":1,"qclass_name":"C_INTERNET","qtype":28,"qtype_name":"AAAA","rcode":0,"rcode_name":"NOERROR","AA":false,"TC":false,"RD":true,"RA":true,"Z":0,"answers":["api.facebook.com","star.c10r.facebook.com","2a03:2880:f01c:20e:face:b00c:0:2"],"TTLs":[1312.0,1204.0,59.0],"rejected":false}]}
MapperParsingException[Field name [id.orig_h] cannot contain '.']
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:276)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:221)
	at org.elasticsearch.index.mapper.object.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:138)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:119)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:100)
	at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:435)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:257)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230)
	at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:458)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:762)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2016-02-05 11:31:02,503][DEBUG][action.admin.indices.mapping.put] [g201] failed to put mappings on indices [[bro-201602050300]], type [http]
MapperParsingException[Field name [id.orig_h] cannot contain '.']
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:276)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:221)
	at org.elasticsearch.index.mapper.object.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:138)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:119)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:100)
	at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:435)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:257)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230)
	at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:458)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:762)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by marcki** [comment]
I've two errors here: a "_timestamp" issue and "failed execution": sample:

[2016-02-12 23:49:52,649][DEBUG]**[action.bulk              ] [Aralune] [bro-201602122100][2] failed to execute bulk item (index) index {[bro-201602122100][conn][AVLXrRxpShUM8H2_NzwU], **source[{"_timestamp":1455317372456,"ts":1455317311524,"uid":"CfUQzQ16wN6iCe2jph","id.orig_h":"fe80::3631:c4ff:fef5:21ef","id.orig_p":134,"id.resp_h":"ff02::1","id.resp_p":133,"proto":"icmp","conn_state":"OTH","local_orig":false,"local_resp":false,"missed_bytes":0,"orig_pkts":1,"orig_ip_bytes":144,"resp_pkts":0,"resp_ip_bytes":0,"tunnel_parents":[]}]}
**MapperParsingException[Field [_timestamp] is a metadata field and cannot be added inside a document. Use the index API request parameters.]*

See https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_mapping_changes.html#_literal__timestamp_literal_and_literal__ttl_literal_deprecated

Versions:
bro version 2.4-272
elasticsearch-2.2

**Comment by 0xxon** [comment]
This is tracked in https://bro-tracker.atlassian.net/browse/BIT-1617 - closing here.
