### ISSUE TITLE
kafka log write cause segmentfault

### ISSUE THREAD

**Issue by zengxg** [bro/bro-plugins#43]
I use broctl start 16 bro process and send logs to kafka. 
I found the logger process crashed.

It crashed in kafka plugin.
I think the reason is reporter->Error() in kafka called QueueEvent, but QueueEvent is not thread-safe.

`#0  SetNext (this=0x0, n=0x7fffe83f2ab0) at /home/bro-2.5/src/Event.h:21
21		void SetNext(Event* n)		{ next_event = n; }

(gdb) bt
#0  SetNext (this=0x0, n=0x7fffe83f2ab0) at /home/bro-2.5/src/Event.h:21
#1  EventMgr::QueueEvent (this=0xc2b420 <mgr>, event=event@entry=0x7fffe83f2ab0) at /home/bro-2.5/src/Event.cc:90
#2  0x00000000005fb5f7 in QueueEvent (obj=0x0, mgr=0x0, aid=0, src=0, vl=0x7fffe87d3f20, h=..., this=<optimized out>) at /home/bro-2.5/src/Event.h:88
#3  Reporter::DoLog (this=0xc7d6d0, prefix=prefix@entry=0x90363d "error", event=..., out=0x0, conn=conn@entry=0x0, addl=addl@entry=0x0, location=location@entry=true, time=time@entry=true, 
    postfix=postfix@entry=0x0, fmt=fmt@entry=0x7ffff3aa0bd0 "Kafka send failed: %s", ap=ap@entry=0x7ffff25feb48) at /home/bro-2.5/src/Reporter.cc:350
#4  0x00000000005fbddf in Reporter::Error (this=<optimized out>, fmt=fmt@entry=0x7ffff3aa0bd0 "Kafka send failed: %s") at /home/bro-2.5/src/Reporter.cc:76
#5  0x00007ffff3a9ee19 in logging::writer::KafkaWriter::DoWrite (this=0x42f52c0, num_fields=<optimized out>, fields=<optimized out>, vals=0x49d3aa0)
    at /home/bro-plugins/kafka/src/KafkaWriter.cc:156
#6  0x0000000000898435 in logging::WriterBackend::Write (this=0x42f52c0, arg_num_fields=<optimized out>, num_writes=1000, vals=0x5094770) at /home/bro-2.5/src/logging/WriterBackend.cc:242
#7  0x000000000065ee77 in threading::MsgThread::Run (this=0x42f52c0) at /home/bro-2.5/src/threading/MsgThread.cc:371
#8  0x000000000065bc68 in threading::BasicThread::launcher (arg=0x42f52c0) at /home/bro-2.5/src/threading/BasicThread.cc:201
#9  0x00007ffff6c66dc5 in start_thread () from /lib64/libpthread.so.0
#10 0x00007ffff5f7073d in clone () from /lib64/libc.so.6`

**Comment by JonZeolla** [comment]
Thanks, I'm working on this as a part of a bigger update to the kafka plugin.  The plan is to eventually migrate it to a bro package and host it [here](https://github.com/apache/incubator-metron-bro-plugin-kafka).  Once I'm semi-confident that I have things working I plan to send an email out to the bro dev mailing list for further testing.
